workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      node: latest
      npm: latest
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/*/.apk